### ISSUE TITLE
Draft June newsletter content

### ISSUE THREAD

**Issue by kristoferlund** [givepraise/planning#19]

**Comment by kristoferlund** [comment]
Should be included in newsletter:
- An excerpt from the blog post #39
- Launch info / "praise now available" / setup yourself / embed video

@ahmadabugosh

**Comment by kristoferlund** [comment]
- AI article - @kristoferlund
- Twitter space
- Road map (https://www.notion.so/giveth/Praise-Public-Development-Roadmap-and-Milestones-7b850beb940c4c0f82c68b9439c7f4d8)

**Comment by ahmadabugosh** [comment]
@anamarija09 Started working on this
