### ISSUE TITLE
Onboarding video

### ISSUE THREAD

**Issue by kristoferlund** [givepraise/planning#8]
Preview here: 
https://replay.dropbox.com/share/GIxRAtEvsn0deFxF

**Comment by kristoferlund** [comment]
@ahmadabugosh I made some comments, see link above. Only small stuff really.

**Comment by ahmadabugosh** [comment]
hey @kristoferlund can we close this issue or is there anything else to work on?

**Comment by kristoferlund** [comment]
video published, great stuff @ahmadabugosh 
https://www.youtube.com/watch?v=AePb_s0AQcw
