### ISSUE TITLE
Set the date for the first OP community session

### ISSUE THREAD

**Issue by justi0** [givepraise/planning#91]

**Comment by franculio** [comment]
Is this referring to the workshop @justi0 ?

**Comment by brichis** [comment]
Hey @franculio when will be the session about Optimism? I need to send more information about that to Justine

**Comment by franculio** [comment]
@brichis let's book a time for tuesday after their community call. Would it be in the mainstage channel that they have? Wdyt?

**Comment by brichis** [comment]
@franculio The Community Call is on Zoom I think we have two options:
1) Ask to Michael to use the same link than the community call so the delegates can stay there (only for Governance Calendar)
2) If we want to do it for all the community, we can ask to use a voice channel on the Optimism Discord (And add it to the public calendar for everyone not only governance)

We will need a catchy name for the event and I think a short description could be great

**Comment by franculio** [comment]
I feel like an open event on Discord is more accessible to the OP community as a whole, and maybe getting someone to announce the event during the community call happening right after is enough.

I agree that we need a catchy name. Tomorrow we can hack together in the sync :)
