### ISSUE TITLE
Plan communication strategy about our activity

### ISSUE THREAD

**Issue by justi0** [givepraise/planning#98]
-Socials
- Graphical material ( OP and Praise logos)

**Comment by EliGior** [comment]
I create two examples of flyers to promote the Community Demo: 
![Praise Community DEMO](https://github.com/givepraise/planning/assets/135726503/0becd319-6284-4f80-83c8-b77932ce88f2)
![Praise Community DEMO 2](https://github.com/givepraise/planning/assets/135726503/e09c1c4f-726f-44bc-bce7-de719de8034d)
